macros:
  - keyword: u
    label: lazy_unknown_talk_idle
    options:
      - name: text
        type: string
  - keyword: k
    label: lazy_kogomi_talk_idle
    options:
      - name: text
        type: string
  - keyword: t
    label: lazy_talk
    options:
      - name: character
        type: string
      - name: text
        type: string
  - keyword: p
    label: lazy_player_talk
    options:
      - name: text
        type: string
  - keyword: tp
    label: lazy_player_think
    options:
      - name: text
        type: string
